# Generated by Django 3.2.13 on 2022-05-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visit_count',
            field=models.IntegerField(default=0),
        ),
    ]
