# Generated by Django 3.2.13 on 2022-05-21 17:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_post_visitors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostViewWithUniqueUser',
            new_name='PostView',
        ),
        migrations.RemoveField(
            model_name='post',
            name='visit_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='visitors',
        ),
    ]
