# Generated by Django 4.0.4 on 2022-06-01 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20220521_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='auther',
        ),
    ]
