# Generated by Django 4.0.4 on 2022-06-16 11:15

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20220614_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteabout',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.upload_image_path, verbose_name='Image'),
        ),
    ]
