# Generated by Django 4.0.4 on 2022-06-22 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_postcategory_title_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='title_cat',
            new_name='title_category',
        ),
    ]
