# Generated by Django 4.0.4 on 2022-07-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_title_cat_postcategory_title_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_tag', models.CharField(blank=True, max_length=200, verbose_name='تگ')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='tag', to='blog.posttag', verbose_name='تگ'),
        ),
    ]
